line:
  bot:
    channel-token: "//SKDQDGJcLBUUveTXfykYJjsRhDqTLM504SaQdWLRV03rIJAVpW5FiK2XL3aiQZnV/M7tfDLVPAn1WBMGkS64bu5a5l7IVrcXFnO+9yDQjKrDM+F2nDA4z+9Cxb8tGqsGQFKmN4pOllTMMOFzDFuQdB04t89/1O/w1cDnyilFU="
    channel-secret: "10492b4200c7d5c4a2ad1bb22f78bb7f"
    handler:
      path: "/callback"

thingsboard:
  host: "https://demo.thingsboard.io"
  username: "quangnam130520@gmail.com"
  password: "Nam130599"