server:
  address: 0.0.0.0
  port: 8080


spring:

  data:
    mongodb:
      uri: mongodb+srv://root:root@hrdept-cluster.1xl9ayf.mongodb.net/?retryWrites=true&w=majority
      database: importFile


jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d99a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  access_token_expiration_second: 1800 # 30 minutes
  refresh_token_expiration_second: 3600